// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDkB_1ZRGISNxLbcqbkQs1umDYjhiqRc',
    appId: '1:698295394667:web:3a25d40e42f273d2e9ac2e',
    messagingSenderId: '698295394667',
    projectId: 'veda-coach',
    authDomain: 'veda-coach.firebaseapp.com',
    storageBucket: 'veda-coach.firebasestorage.app',
    measurementId: 'G-NMGW54TKNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl9rhC8BKZlV5FwpTTbS4Nkp9J3kQNVQE',
    appId: '1:698295394667:android:63bb3dc1159f452fe9ac2e',
    messagingSenderId: '698295394667',
    projectId: 'veda-coach',
    storageBucket: 'veda-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfX33XiHpBVH3YCkCyw5CXGYXYHP1XpNY',
    appId: '1:698295394667:ios:97e0bd6dd2f29936e9ac2e',
    messagingSenderId: '698295394667',
    projectId: 'veda-coach',
    storageBucket: 'veda-coach.firebasestorage.app',
    iosBundleId: 'com.example.vedaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfX33XiHpBVH3YCkCyw5CXGYXYHP1XpNY',
    appId: '1:698295394667:ios:97e0bd6dd2f29936e9ac2e',
    messagingSenderId: '698295394667',
    projectId: 'veda-coach',
    storageBucket: 'veda-coach.firebasestorage.app',
    iosBundleId: 'com.example.vedaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDkB_1ZRGISNxLbcqbkQs1umDYjhiqRc',
    appId: '1:698295394667:web:73bb8ddb8945f64be9ac2e',
    messagingSenderId: '698295394667',
    projectId: 'veda-coach',
    authDomain: 'veda-coach.firebaseapp.com',
    storageBucket: 'veda-coach.firebasestorage.app',
    measurementId: 'G-B1GYT7472Q',
  );
}
